### ISSUE TITLE
Criação do Documento de Arquitetura

### ISSUE THREAD

**Issue by thiagorfreitas** [fga-eps-mds/2023.1-GuiaUnB#22]
## Descrição da Issue
Criar um documento de arquitetura para o projeto "GuiaUnB", um aplicativo móvel desenvolvido em Flutter e Dart com o objetivo de informar os alunos da Universidade de Brasília (UnB) sobre seus direitos como estudantes.

## Tasks:
- [x] Pesquisar e selecionar uma metodologia de arquitetura para o projeto.
- [x] Definir as camadas da arquitetura escolhida e suas responsabilidades.
- [x] Descrever as tecnologias utilizadas na arquitetura e seus motivos de escolha.
- [x] Descrever as funcionalidades e componentes da arquitetura do aplicativo.
- [x] Identificar possíveis pontos de melhoria na arquitetura e sugestões para otimização.

## Critérios de Aceitação:
- [x] O documento de arquitetura deve seguir a metodologia selecionada e apresentar as camadas definidas com suas respectivas responsabilidades.
- [x] As tecnologias utilizadas na arquitetura devem ser descritas e justificadas.
- [x] O diagrama de arquitetura deve ser criado e apresentar uma representação clara da estrutura do aplicativo.
- [x] Os requisitos não-funcionais do aplicativo devem ser identificados e descritos na arquitetura.
- [x] Sugestões de melhoria e otimização devem ser apresentadas no documento.

## Assignees
@thiagorfreitas @ArthurGabrieel 

## Milestone
Sprint 4

## Estimate
5 pontos
