### ISSUE TITLE
Criação de um Documento de Políticas de Segurança

### ISSUE THREAD

**Issue by thiagorfreitas** [fga-eps-mds/2023.1-GuiaUnB#23]
## Descrição da Issue
Criação de um documento de Política de Segurança para garantir a proteção dos dados e informações sensíveis do projeto GuiaUnb e de seus usuários.

## Tasks:
- [x] Realizar uma pesquisa sobre políticas de segurança para projetos similares
- [x] Definir as diretrizes da política de segurança
- [x] Elaborar o documento de Política de Segurança
- [x] Revisão e aprovação final do documento

## Critérios de Aceitação:
- [x] O documento deve seguir as normas e boas práticas de segurança de informações
- [x] O documento deve contemplar a proteção dos dados dos clientes e informações sensíveis da empresa
- [x] O documento deve ser revisado e aprovado pelo responsável pela área de segurança da informação

## Assignees
@ArthurGabrieel 

## Milestone
Sprint 4

## Estimate
5 pontos
