### ISSUE TITLE
Atualização e melhoria no README

### ISSUE THREAD

**Issue by thiagorfreitas** [fga-eps-mds/2023.1-GuiaUnB#24]
## Descrição da Issue
Realizar atualizações e melhorias no README do projeto, incluindo informações mais precisas e relevantes sobre o projeto e suas funcionalidades.

## Tasks:
- [x] Atualizar a seção de descrição do projeto
- [x] Incluir informações sobre como instalar e executar o projeto
- [x] Incluir exemplos de uso do projeto
- [x] Adicionar seções sobre as tecnologias utilizadas e a equipe de desenvolvimento

## Critérios de Aceitação:
- [x] O README deve conter uma descrição clara e concisa do projeto
- [x] As instruções de instalação e execução devem ser precisas e fáceis de seguir
- [x] Os exemplos de uso devem ser relevantes e úteis para o usuário
- [x] As seções sobre as tecnologias e a equipe de desenvolvimento devem ser informativas e relevantes para o projeto

## Assignees
@ArthurGabrieel 

## Milestone
Sprint 4

## Estimate
2 pontos
