### ISSUE TITLE
Criação de um Documento de Padronização de Branches

### ISSUE THREAD

**Issue by thiagorfreitas** [fga-eps-mds/2023.1-GuiaUnB#25]
## Descrição da Issue
Será criado um documento para definir as regras de padronização dos branches a serem utilizados no repositório do projeto GuiaUnB.

## Tasks:
- [x] Definir as regras de padronização dos nomes dos branches;
- [x] Definir os tipos de branches que poderão ser criados e suas finalidades;
- [x] Documentar as regras de merge e rebase a serem utilizadas nos branches;
- [x] Especificar as permissões de acesso aos branches, de acordo com as funções dos colaboradores do projeto.

## Critérios de Aceitação:
- [x] O documento deve estar completo e detalhado, contemplando todas as regras definidas;
- [x] As regras definidas devem ser adotadas pelos colaboradores do projeto;
- [x] O documento deve ser revisado por pelo menos um outro colaborador antes de ser considerado concluído.

## Assignees
@thiagorfreitas 

## Milestone
Sprint 4

## Estimate
5 pontos.
