### ISSUE TITLE
Criação de um Documento de Padronização de Commits

### ISSUE THREAD

**Issue by thiagorfreitas** [fga-eps-mds/2023.1-GuiaUnB#26]
## Descrição da Issue
Criar um padrão para os commits no projeto GuiaUnB, com o objetivo de garantir a clareza e a organização do histórico de alterações.

## Tasks:
- [x] Definir o padrão de commit
- [x] Comunicar o padrão aos colaboradores do projeto
- [x] Realizar revisão dos commits existentes e ajustá-los ao novo padrão

## Critérios de Aceitação:
- [x] O padrão de commit deve ser claro e de fácil entendimento pelos colaboradores do projeto
- [x] Todos os colaboradores do projeto devem estar cientes do novo padrão
- [x] Todos os commits realizados após a definição do novo padrão devem seguir o mesmo

## Assignees
@ArthurGabrieel 

## Milestone
Sprint 5

## Estimate
Estimativa: 3 pontos.
