### ISSUE TITLE
Criação de um Documento de Plano de Comunicação

### ISSUE THREAD

**Issue by thiagorfreitas** [fga-eps-mds/2023.1-GuiaUnB#27]
## Descrição da Issue
Nesta issue, será criado um documento de plano de comunicação para o projeto, que definirá como a comunicação será estabelecida entre os membros da equipe, bem como com o cliente e outras partes interessadas. 

## Tasks:
- [x] Definir quais canais de comunicação serão utilizados (e-mail, chat, reuniões, etc.)
- [x] Identificar as partes interessadas no projeto e estabelecer um plano de comunicação específico para cada uma delas
- [x] Definir a linguagem a ser utilizada na comunicação, considerando o público-alvo de cada mensagem
- [x] Criar um documento formal do plano de comunicação

## Critérios de Aceitação:
- [x] O documento deve estar completo e abranger todos os aspectos relevantes da comunicação no projeto
- [x] O documento deve ser aprovado pelo cliente e pelos membros da equipe
- [x] Todas as partes interessadas devem estar cientes e satisfeitas com o plano de comunicação estabelecido

## Assignees
@ArthurGabrieel @thiagorfreitas 

## Milestone
Sprint 5

## Estimate
5 pontos
