### ISSUE TITLE
Criação do Documento de Visão

### ISSUE THREAD

**Issue by thiagorfreitas** [fga-eps-mds/2023.1-GuiaUnB#29]
## Descrição da Issue
Criar o Documento de Visão, que deve descrever de forma clara e objetiva o objetivo do projeto, seus principais requisitos, as funcionalidades esperadas, o público-alvo, além de outras informações relevantes para o entendimento do escopo do projeto.

## Tasks:
- [x] Levantamento dos principais objetivos do projeto
- [x] Identificação e descrição dos principais requisitos do projeto
- [x] Definição das funcionalidades esperadas do projeto
- [x] Identificação do público-alvo do projeto
- [x] Descrição das informações relevantes para o entendimento do escopo do projeto

## Critérios de Aceitação:
- [x] Documento de Visão completo e bem estruturado
- [x] Objetivos, requisitos, funcionalidades e público-alvo bem definidos e descritos de forma clara e objetiva
- [x] Informações relevantes para o entendimento do escopo do projeto claramente identificadas e descritas
- [x] Documento revisado e aprovado pelo time

## Assignees
@thiagorfreitas @ArthurGabrieel 

## Milestone
Sprint 5

## Estimate
4 pontos.
