### ISSUE TITLE
Criação do Documento de Contribuição

### ISSUE THREAD

**Issue by thiagorfreitas** [fga-eps-mds/2023.1-GuiaUnB#31]
## Descrição da Issue
O objetivo desta issue é criar um documento de contribuição para o projeto, descrevendo as diretrizes que os colaboradores devem seguir ao contribuir com o código fonte, documentação, testes e demais artefatos do projeto Guia UnB.

## Tasks:
- [x] Definir as seções do documento de contribuição
- [x] Escrever o conteúdo das seções
- [x] Revisar o documento
- [x] Publicar o documento na pasta "docs" do repositório

## Critérios de Aceitação:
- [x] O documento de contribuição deve estar completo e bem escrito
- [x] O documento deve ser revisado por pelo menos dois colaboradores
- [x] O documento deve estar publicado na pasta "docs" do repositório

## Assignees
@ArthurGabrieel

## Milestone
Sprint 3

## Estimate
2 pontos.
