### ISSUE TITLE
Criação da Documentação das Sprints passadas

### ISSUE THREAD

**Issue by thiagorfreitas** [fga-eps-mds/2023.1-GuiaUnB#32]
## Descrição da Issue
Criar a documentação das sprints passadas para o projeto, a fim de garantir o registro do planejamento de cada sprint, as atividades realizadas, e os resultados alcançados, nas sprints 0 até 5.

## Tasks:
- [x] Revisar as atas das reuniões das sprints passadas;
- [x] Elaborar um documento para cada sprint, com informações sobre objetivos, atividades realizadas, resultados alcançados;
- [x] Revisar e editar os documentos criados;
- [x] Inserir os documentos no repositório do projeto.

## Critérios de Aceitação:
- [x] Documentação completa das sprints passadas, com informações sobre objetivos, atividades realizadas, resultados alcançados
- [x] Documentos revisados e editados de forma clara e concisa;
- [x] Documentos inseridos no repositório do projeto.

## Assignees
@ArthurGabrieel @thiagorfreitas @zzzBECK @igor-ribeir0 

## Labels
documentation, sprint

## Milestone
Sprint 5

## Estimate
5 pontos.
