### ISSUE TITLE
Criar estrutura inicial do projeto

### ISSUE THREAD

**Issue by ArthurGabrieel** [fga-eps-mds/2023.1-GuiaUnB#36]
## Descrição da Issue
Criação da parte de navegação entre as telas do app.
## Tasks:
- [x] Criar estrutura das páginas.
- [x] Fazer a lógica de navegação entre páginas.

## Critérios de Aceitação:
- [x] O app está funcionando corretamente.
