### ISSUE TITLE
Documentar sprint 6

### ISSUE THREAD

**Issue by ArthurGabrieel** [fga-eps-mds/2023.1-GuiaUnB#37]
## Descrição da Issue
Fazer a documentação da sprint 6

## Tasks:
- [x] Documentar o planejamento da sprint
- [x] Documentar o resultado da sprint

## Critérios de Aceitação:
- [x] Está seguindo o padrão do projeto
