### ISSUE TITLE
Criar protótipo de alta fidelidade

### ISSUE THREAD

**Issue by ArthurGabrieel** [fga-eps-mds/2023.1-GuiaUnB#41]
## Descrição da Issue
Criar um protótipo de alta fidelidade para o aplicativo Guia UnB, visando melhorar a experiência do usuário e tornar a navegação mais intuitiva.

## Tasks:
- [x] Escolher as principais funcionalidades do aplicativo a serem contempladas no protótipo.
- [x] Definir o fluxo de navegação entre as telas.
- [x] Escolher a ferramenta de prototipagem e criar as telas do protótipo.
- [x] Testar e validar o protótipo com usuários e realizar as adaptações necessárias.

## Critérios de Aceitação:
- [x]  O protótipo deve contemplar as principais funcionalidades do aplicativo.
- [x] O fluxo de navegação deve ser intuitivo e facilitar o acesso às informações.
- [x] O protótipo deve ser visualmente atrativo e seguir as diretrizes de design do aplicativo.
- [x] O protótipo deve ser testado e validado com usuários, com base em um roteiro de testes previamente elaborado.
- [x] As adaptações necessárias devem ser realizadas a partir dos resultados dos testes.
