### ISSUE TITLE
Criar documentos de personas

### ISSUE THREAD

**Issue by ArthurGabrieel** [fga-eps-mds/2023.1-GuiaUnB#42]
## Descrição da Issue
Criar documentos de personas para o projeto

## Tasks:
- [x] Pesquisar informações relevantes sobre o público-alvo do Guia UnB
- [x] Identificar características e necessidades comuns do público-alvo
- [x] Criar no mínimo duas personas baseadas nas informações coletadas
- [x] Documentar as personas criadas em um arquivo de texto ou em um modelo de documento padrão definido pelo projeto

## Critérios de Aceitação:
- [x] As personas devem ser baseadas em informações reais e relevantes sobre o público-alvo do projeto
- [x] As personas devem incluir informações como idade, gênero, nível de escolaridade, principais desafios e objetivos, etc.
- [x] As personas devem ser apresentadas de forma clara e organizada, em um formato que possa ser facilmente compartilhado e utilizado pelos membros do projeto.
