### ISSUE TITLE
Responder dúvidas do Backlog

### ISSUE THREAD

**Issue by zzzBECK** [fga-eps-mds/2023.1-GuiaUnB#56]
## Descrição da Issue
Separar as respostas das dúvidas previamente selecionadas no Backlog FT05

## Tasks:
- [ ] Catalogar as dúvidas
- [ ] Separar as respostas

## Critérios de Aceitação:
- [ ] Repostas devidamente corretas segundo documentação oficial da UnB
- [ ] Informações relevantes para fácil entendimento

## Estimate
3
