### ISSUE TITLE
Mostrar tela de Onboarding apenas na primeira execução do aplicativo

### ISSUE THREAD

**Issue by ArthurGabrieel** [fga-eps-mds/2023.1-GuiaUnB#66]
## Descrição da Issue
Nesta tarefa, será implementada a funcionalidade de exibir a tela de Onboarding somente na primeira vez que o usuário abrir o aplicativo. O objetivo é fornecer uma introdução ao aplicativo e suas principais funcionalidades para novos usuários.

## Tasks:
- [x] Adicionar uma flag de controle para verificar se o usuário já visualizou a tela de Onboarding.
- [x] Ao iniciar o aplicativo, verificar se a flag está definida.
- [x] Caso a flag esteja definida, direcionar o usuário para a tela principal do aplicativo.
- [x] Caso a flag não esteja definida, exibir a tela de Onboarding.
- [x] Após o usuário concluir o Onboarding, definir a flag como true para que não seja exibida novamente nas próximas execuções do aplicativo.

## Critérios de Aceitação:
- A tela de Onboarding deve ser exibida apenas na primeira execução do aplicativo.
- Após o usuário concluir o Onboarding, a tela principal do aplicativo deve ser exibida nas próximas execuções.
- A flag de controle deve ser corretamente implementada e atualizada após o término do Onboarding.

## Estimate
A estimativa de dificuldade para essa tarefa é de 2 pontos, considerando o trabalho necessário para adicionar a flag de controle, verificar e redirecionar o usuário corretamente, e atualizar a flag após o término do Onboarding, levando em consideração os critérios estabelecidos no [documento de contribuição](https://github.com/fga-eps-mds/2023.1-GuiaUnB/blob/main/CONTRIBUTING.md).
