### ISSUE TITLE
Adicionar ícone para o aplicativo

### ISSUE THREAD

**Issue by ArthurGabrieel** [fga-eps-mds/2023.1-GuiaUnB#79]
## Descrição da Issue
Atualmente, o aplicativo não possui um ícone personalizado e está utilizando o ícone padrão do sistema. É importante adicionar um ícone exclusivo que represente a identidade visual do aplicativo.

## Tasks:
- [x] Projetar um ícone exclusivo para o aplicativo
- [x] Converter o ícone para os formatos necessários (por exemplo, PNG, SVG)
- [x] Adicionar o ícone aos recursos do projeto
- [x] Atualizar o manifesto do aplicativo para usar o novo ícone

## Critérios de Aceitação:
- [x] O ícone deve ser visualmente atraente e representar a identidade visual do aplicativo
- [x] O ícone deve estar disponível nos formatos adequados para uso no aplicativo
- [x] O ícone deve ser adicionado corretamente aos recursos do projeto
- [x] O manifesto do aplicativo deve ser atualizado para utilizar o novo ícone

## Estimate
A dificuldade será de 2 pontos, levando em consideração os critérios estabelecidos no [documento de contribuição](https://github.com/fga-eps-mds/2023.1-GuiaUnB/blob/main/CONTRIBUTING.md).
